
# Auto-generated by run_rom_pipeline.py v2 — edit the script, not this file.
DATA_ROOT = r"/content/rom_work/data/"
METAINFO  = r"/content/rom_work/ankle_v2_metainfo.py"
load_from = '/content/drive/MyDrive/ROM/pretrained/hrnet_w32_coco_256x192-c78dce93_20200708.pth'

default_scope = 'mmpose'
resume = False
randomness = dict(seed=0, deterministic=False)

# UDP codec: continuous-coordinate affine, no half-cell bias.
# (w, h) = 384x512, portrait 3:4 like the source photos -> no distortion.
codec = dict(type='UDPHeatmap', input_size=(384, 512),
             heatmap_size=(96, 128), sigma=2.0)

model = dict(
    type='TopdownPoseEstimator',
    data_preprocessor=dict(
        type='PoseDataPreprocessor',
        mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375],
        bgr_to_rgb=True),
    backbone=dict(
        type='HRNet', in_channels=3,
        extra=dict(
            stage1=dict(num_modules=1, num_branches=1, block='BOTTLENECK',
                        num_blocks=(4, ), num_channels=(64, )),
            stage2=dict(num_modules=1, num_branches=2, block='BASIC',
                        num_blocks=(4, 4), num_channels=(32, 64)),
            stage3=dict(num_modules=4, num_branches=3, block='BASIC',
                        num_blocks=(4, 4, 4), num_channels=(32, 64, 128)),
            stage4=dict(num_modules=3, num_branches=4, block='BASIC',
                        num_blocks=(4, 4, 4, 4),
                        num_channels=(32, 64, 128, 256)))),
    head=dict(
        type='HeatmapHead',
        in_channels=32,
        out_channels=3,      # bottom_heel, 5th_metatarsal, malleolus
        deconv_out_channels=None, deconv_kernel_sizes=None,
        loss=dict(type='AdaptiveWingLoss', alpha=2.1, omega=14, epsilon=1,
                  theta=0.5, use_target_weight=True,
                  loss_weight=1.0),
        decoder=codec),
    test_cfg=dict(flip_test=False, shift_heatmap=False))

backend_args = dict(backend='local')

train_pipeline = [
    dict(type='LoadImage', backend_args=backend_args),
    dict(type='GetBBoxCenterScale', padding=1.0),
    # no flip: left and right feet are not interchangeable
    dict(type='RandomBBoxTransform',
         shift_factor=0.16, shift_prob=0.5,
         scale_factor=(0.88, 1.12), scale_prob=1.0,
         rotate_factor=5.0, rotate_prob=0.6),
    dict(type='TopdownAffine', input_size=codec['input_size'], use_udp=True),
    dict(type='Albumentation', transforms=[
        dict(type='RandomBrightnessContrast', brightness_limit=0.35,
             contrast_limit=0.35, p=0.7),
        dict(type='HueSaturationValue', hue_shift_limit=10, sat_shift_limit=25,
             val_shift_limit=20, p=0.5),
        dict(type='RandomGamma', gamma_limit=(70, 130), p=0.3),
        dict(type='GaussNoise', var_limit=(5.0, 40.0), p=0.3),
        dict(type='MotionBlur', blur_limit=5, p=0.2),
        dict(type='ImageCompression', quality_lower=60, quality_upper=100, p=0.3),
        dict(type='CoarseDropout', max_holes=4, max_height=24, max_width=24,
             min_holes=1, fill_value=0, p=0.2),
    ]),
    dict(type='GenerateTarget', encoder=codec, use_dataset_keypoint_weights=True),
    dict(type='PackPoseInputs')
]

val_pipeline = [
    dict(type='LoadImage', backend_args=backend_args),
    dict(type='GetBBoxCenterScale', padding=1.0),
    dict(type='TopdownAffine', input_size=codec['input_size'], use_udp=True),
    dict(type='PackPoseInputs')
]

dataset_type = 'CocoDataset'
data_mode = 'topdown'

train_dataloader = dict(
    batch_size=4, num_workers=2, persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(type=dataset_type, data_root=DATA_ROOT, data_mode=data_mode,
                 ann_file='annotations/train.json',
                 data_prefix=dict(img='images/'),
                 metainfo=dict(from_file=METAINFO),
                 pipeline=train_pipeline))

# monitor.json = images FROM TRAIN (in-sample). Convergence only.
val_dataloader = dict(
    batch_size=4, num_workers=2, persistent_workers=True, drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False, round_up=False),
    dataset=dict(type=dataset_type, data_root=DATA_ROOT, data_mode=data_mode,
                 ann_file='annotations/monitor.json',
                 data_prefix=dict(img='images/'),
                 metainfo=dict(from_file=METAINFO),
                 test_mode=True, pipeline=val_pipeline))
test_dataloader = val_dataloader

val_evaluator = [
    dict(type='PCKAccuracy', thr=0.005, norm_item='bbox'),
    dict(type='EPE'),
    dict(type='AnkleAngleMetric'),
]
test_evaluator = val_evaluator

train_cfg = dict(by_epoch=True, max_epochs=160, val_interval=10)
val_cfg = dict()
test_cfg = dict()

optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(type='AdamW', lr=2e-4, weight_decay=0.05),
    paramwise_cfg=dict(custom_keys={'backbone': dict(lr_mult=0.1)}),
    clip_grad=dict(max_norm=1.0, norm_type=2))

# 56 images / batch 4 = 14 iters/epoch x 160 = 2240 iters
param_scheduler = [
    dict(type='LinearLR', start_factor=0.01, by_epoch=False, begin=0, end=150),
    dict(type='CosineAnnealingLR', by_epoch=True, begin=0, end=160,
         T_max=160, eta_min=2e-6, convert_to_iter_based=True),
]
auto_scale_lr = dict(base_batch_size=512)

default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=10),
    param_scheduler=dict(type='ParamSchedulerHook'),
    # save_best OFF: the LAST epoch is used, so the test set stays clean.
    # Written straight to Drive every 20 epochs -> survives a disconnect.
    checkpoint=dict(type='CheckpointHook', interval=20,
                    max_keep_ckpts=1, save_last=True),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(type='PoseVisualizationHook', enable=False))

custom_hooks = [
    dict(type='EMAHook', ema_type='ExpMomentumEMA', momentum=0.005,
         update_buffers=True, priority=49),
]

env_cfg = dict(cudnn_benchmark=False,
               mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
               dist_cfg=dict(backend='nccl'))
vis_backends = [dict(type='LocalVisBackend')]
visualizer = dict(type='PoseLocalVisualizer', vis_backends=vis_backends,
                  name='visualizer')
log_processor = dict(type='LogProcessor', window_size=20, by_epoch=True,
                     num_digits=6)
log_level = 'INFO'
