
# Auto-generated by run_rom_pipeline.py — do not hand-edit; edit the script.
DATA_ROOT = r"/content/rom_work/data/"
METAINFO  = r"/content/rom_work/ankle3_metainfo.py"
load_from = None

default_scope = 'mmpose'
resume = False
randomness = dict(seed=0, deterministic=False)

# ------------------------------------------------------------------- codec
# UDPHeatmap, not MSRAHeatmap: UDP defines the affine transform in CONTINUOUS
# coordinates. MSRA's discrete formulation leaves a ~0.5 heatmap-cell bias,
# which at stride 4 on a 5712 px frame is ~17 px ~ 0.8 deg — and it does NOT
# cancel between the rest and dorsiflexion frames.
# input_size is (w, h): portrait, exactly 3:4 like the source files, so a
# full-frame bbox warps with zero aspect distortion.
codec = dict(type='UDPHeatmap', input_size=(384, 512),
             heatmap_size=(96, 128), sigma=2.0)

# ------------------------------------------------------------------- model
model = dict(
    type='TopdownPoseEstimator',
    data_preprocessor=dict(
        type='PoseDataPreprocessor',
        mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375],
        bgr_to_rgb=True),
    # HRNet-W32, not W18. There is NO HRNet-W18 COCO top-down checkpoint in the
    # OpenMMLab pose zoo — W18 ships there only as HRNetV2 for hand/face. The
    # zoo carries W32 and W48 for COCO body, which is why the W18 URLs 404'd and
    # the previous run trained from random init and collapsed to a constant.
    # NO frozen_stages here: freezing the stem at random init was half of that
    # collapse. Every stage trains; the backbone is merely slowed by lr_mult.
    backbone=dict(
        type='HRNet', in_channels=3,
        extra=dict(
            stage1=dict(num_modules=1, num_branches=1, block='BOTTLENECK',
                        num_blocks=(4, ), num_channels=(64, )),
            stage2=dict(num_modules=1, num_branches=2, block='BASIC',
                        num_blocks=(4, 4), num_channels=(32, 64)),
            stage3=dict(num_modules=4, num_branches=3, block='BASIC',
                        num_blocks=(4, 4, 4), num_channels=(32, 64, 128)),
            stage4=dict(num_modules=3, num_branches=4, block='BASIC',
                        num_blocks=(4, 4, 4, 4),
                        num_channels=(32, 64, 128, 256)))),
    head=dict(
        type='HeatmapHead',
        in_channels=32,      # HRNet-W32 high-resolution branch width
        out_channels=3,      # bottom_heel, 5th_metatarsal, shin
        deconv_out_channels=None, deconv_kernel_sizes=None,
        # AdaptiveWingLoss over MSE: MSE is dominated by the ~99% of cells that
        # are background, so it optimises "not a peak" rather than "exactly
        # where the peak is". AWing was built for sub-pixel landmarks.
        # CAUTION: AWing's magnitude is orders larger than MSE's. On NaN or
        # early divergence, drop loss_weight to 0.1 before touching lr.
        loss=dict(type='AdaptiveWingLoss', alpha=2.1, omega=14, epsilon=1,
                  theta=0.5,
                  use_target_weight=True,      # activates joint_weights
                  loss_weight=1.0),
        decoder=codec),
    test_cfg=dict(
        flip_test=False,      # single-sided rig, never mirrored
        shift_heatmap=False)) # UDP already refines; don't double-correct

# ------------------------------------------------------------------- pipelines
backend_args = dict(backend='local')

train_pipeline = [
    dict(type='LoadImage', backend_args=backend_args),
    # padding=1.0, not the 1.25 default: the bbox IS the full frame, so 1.25
    # would pad 25% black everywhere and shrink pixels-on-target.
    dict(type='GetBBoxCenterScale', padding=1.0),
    # no RandomFlip anywhere.
    dict(type='RandomBBoxTransform',
         shift_factor=0.16, shift_prob=0.5,
         scale_factor=(0.88, 1.12), scale_prob=1.0,
         rotate_factor=5.0, rotate_prob=0.6),
    # use_udp=True MUST match the codec AND the val pipeline. A mismatch is the
    # commonest silent 0.5-1 deg bug in this whole setup.
    dict(type='TopdownAffine', input_size=codec['input_size'], use_udp=True),
    # photometric only: geometry is handled above, and elastic/grid distortion
    # would move landmarks non-rigidly and corrupt the labels.
    dict(type='Albumentation', transforms=[
        dict(type='RandomBrightnessContrast', brightness_limit=0.35,
             contrast_limit=0.35, p=0.7),
        dict(type='HueSaturationValue', hue_shift_limit=10, sat_shift_limit=25,
             val_shift_limit=20, p=0.5),
        dict(type='RandomGamma', gamma_limit=(70, 130), p=0.3),
        dict(type='GaussNoise', var_limit=(5.0, 40.0), p=0.3),
        dict(type='MotionBlur', blur_limit=5, p=0.2),
        dict(type='ImageCompression', quality_lower=60, quality_upper=100, p=0.3),
        dict(type='CoarseDropout', max_holes=4, max_height=24, max_width=24,
             min_holes=1, fill_value=0, p=0.2),
    ]),
    # use_dataset_keypoint_weights=True is what actually applies
    # joint_weights=[1.5, 1.0, 1.0]. Without it the weights are silently ignored.
    dict(type='GenerateTarget', encoder=codec, use_dataset_keypoint_weights=True),
    dict(type='PackPoseInputs')
]

val_pipeline = [
    dict(type='LoadImage', backend_args=backend_args),
    dict(type='GetBBoxCenterScale', padding=1.0),
    dict(type='TopdownAffine', input_size=codec['input_size'], use_udp=True),
    dict(type='PackPoseInputs')
]

# ------------------------------------------------------------------- data
dataset_type = 'CocoDataset'
data_mode = 'topdown'

train_dataloader = dict(
    batch_size=4, num_workers=2, persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(type=dataset_type, data_root=DATA_ROOT, data_mode=data_mode,
                 ann_file='annotations/train.json',
                 data_prefix=dict(img='images/'),
                 metainfo=dict(from_file=METAINFO),
                 pipeline=train_pipeline))

# monitor.json = 8 images FROM TRAIN. In-sample: watches convergence only.
val_dataloader = dict(
    batch_size=4, num_workers=2, persistent_workers=True, drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False, round_up=False),
    dataset=dict(type=dataset_type, data_root=DATA_ROOT, data_mode=data_mode,
                 ann_file='annotations/monitor.json',
                 data_prefix=dict(img='images/'),
                 metainfo=dict(from_file=METAINFO),
                 test_mode=True, pipeline=val_pipeline))
test_dataloader = val_dataloader

# PCK thr is a FRACTION of the bbox, and the bbox is the whole 5712 px frame —
# the 0.05 default would be a 285 px tolerance. 0.003 is ~17 px.
val_evaluator = [
    dict(type='PCKAccuracy', thr=0.003, norm_item='bbox'),
    dict(type='EPE'),
    dict(type='AnkleAngleMetric'),
]
test_evaluator = val_evaluator

# ------------------------------------------------------------------- schedule
train_cfg = dict(by_epoch=True, max_epochs=160, val_interval=10)
val_cfg = dict()
test_cfg = dict()

optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(type='AdamW', lr=2e-4, weight_decay=0.05),
    # lr_mult 0.1, not 0.05: sub-pixel precision in a new domain needs the
    # high-resolution branches to actually move. This is only correct because
    # load_from now supplies genuinely pretrained COCO weights — gently
    # fine-tuning a RANDOM backbone at 2e-5 is what produced the constant
    # prediction last run.
    paramwise_cfg=dict(custom_keys={'backbone': dict(lr_mult=0.1)}),
    clip_grad=dict(max_norm=1.0, norm_type=2))   # AWing can spike early

# 29 rig images / batch 4 = 7 iters per epoch, so 160
# epochs is only ~1120 iterations. A 500-iter warmup would eat a third of
# training; 150 is enough.
param_scheduler = [
    dict(type='LinearLR', start_factor=0.01, by_epoch=False, begin=0, end=150),
    dict(type='CosineAnnealingLR', by_epoch=True, begin=0, end=160,
         T_max=160, eta_min=2e-6, convert_to_iter_based=True),
]
auto_scale_lr = dict(base_batch_size=512)

# ------------------------------------------------------------------- runtime
default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=10),
    param_scheduler=dict(type='ParamSchedulerHook'),
    # save_best is OFF deliberately. With no clean validation set, any "best"
    # checkpoint would be selected on data we also report on. The LAST epoch is
    # used instead: cosine-to-2e-6 plus EMA makes it stable, and it keeps the
    # hold-out statistically honest.
    checkpoint=dict(type='CheckpointHook', interval=40, max_keep_ckpts=2,
                    save_last=True),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(type='PoseVisualizationHook', enable=False))

# momentum 0.005, not the stock 0.0002. EMA's effective window is ~1/momentum
# iterations: 0.0002 -> 5000 iters, LONGER than this entire run, so the EMA
# weights would barely leave their initialisation. 0.005 -> ~200 iters, which
# at 7 iters/epoch is ~29 epochs — the right amount of smoothing
# at this dataset size.
custom_hooks = [
    dict(type='EMAHook', ema_type='ExpMomentumEMA', momentum=0.005,
         update_buffers=True, priority=49),
]

env_cfg = dict(cudnn_benchmark=False,
               mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
               dist_cfg=dict(backend='nccl'))
vis_backends = [dict(type='LocalVisBackend')]
visualizer = dict(type='PoseLocalVisualizer', vis_backends=vis_backends,
                  name='visualizer')
log_processor = dict(type='LogProcessor', window_size=20, by_epoch=True,
                     num_digits=6)
log_level = 'INFO'
